const categories = [
  { label: '' },
  { label: 'Animals', value: 1 },
  { label: 'Buildings and Architecture', value: 2 },
  { label: 'Business', value: 3 },
  { label: 'Drinks', value: 4 },
  { label: 'The Environment', value: 5 },
  { label: 'States of Mind', value: 6 },
  { label: 'Food', value: 7 },
  { label: 'Graphic Resources', value: 8 },
  { label: 'Hobbies and Leisure', value: 9 },
  { label: 'Industry', value: 10 },
  { label: 'Landscapes', value: 11 },
  { label: 'Lifestyle', value: 12 },
  { label: 'People', value: 13 },
  { label: 'Plants and Flowers', value: 14 },
  { label: 'Culture and Religion', value: 15 },
  { label: 'Science', value: 16 },
  { label: 'Social Issues', value: 17 },
  { label: 'Sports', value: 18 },
  { label: 'Technology', value: 19 },
  { label: 'Transport', value: 20 },
  { label: 'Travel', value: 21 },
];

export { categories };
